/* Bilingual glossary: [topic id, English term, Indonesian term, English definition, Indonesian definition] */
const GLOSSARY = [
  ["geo-concepts", "spatial approach", "pendekatan keruangan", "Studying phenomena by where they are and how they spread across space.", "Mengkaji gejala berdasarkan letak dan persebarannya di ruang."],
  ["geo-concepts", "absolute location", "lokasi absolut", "A position given by coordinates of latitude and longitude.", "Letak yang dinyatakan dengan koordinat lintang dan bujur."],
  ["geo-concepts", "relative location", "lokasi relatif", "A position described in relation to other places.", "Letak yang dinyatakan berdasarkan hubungannya dengan tempat lain."],
  ["map-scale", "map scale", "skala peta", "The ratio between a distance on the map and the real distance on the ground.", "Perbandingan antara jarak di peta dan jarak sebenarnya di lapangan."],
  ["map-scale", "legend", "legenda", "The key that explains the symbols and colours on a map.", "Keterangan yang menjelaskan simbol dan warna pada peta."],
  ["coordinates", "latitude", "lintang", "The angle north or south of the equator.", "Sudut di utara atau selatan khatulistiwa."],
  ["coordinates", "longitude", "bujur", "The angle east or west of the prime meridian at Greenwich.", "Sudut di timur atau barat meridian utama di Greenwich."],
  ["coordinates", "equator", "khatulistiwa (ekuator)", "The line of latitude 0° that divides the Earth into two hemispheres.", "Garis lintang 0° yang membagi Bumi menjadi dua belahan."],
  ["time-zones", "time zone", "zona waktu", "A region that uses the same standard time; each 15° of longitude is about one hour.", "Wilayah yang memakai waktu baku yang sama; setiap 15° bujur kira-kira satu jam."],
  ["projections", "map projection", "proyeksi peta", "A method of showing the curved Earth on a flat map.", "Cara menggambarkan permukaan Bumi yang lengkung pada peta datar."],
  ["contours", "contour line", "garis kontur", "A line on a map joining points of equal height.", "Garis pada peta yang menghubungkan titik-titik yang sama tingginya."],
  ["remote-sensing", "remote sensing", "penginderaan jauh", "Gathering information about the Earth from satellites or aircraft without touching it.", "Memperoleh informasi tentang permukaan Bumi dari satelit atau pesawat tanpa menyentuhnya."],
  ["gis", "Geographic Information System (GIS)", "Sistem Informasi Geografis (SIG)", "A computer system for storing, analysing and mapping spatial data.", "Sistem komputer untuk menyimpan, menganalisis, dan memetakan data spasial."],
  ["earth-structure", "crust", "kerak Bumi", "The thin, rocky outer layer of the Earth.", "Lapisan terluar Bumi yang tipis dan berbatu."],
  ["earth-structure", "mantle", "mantel (selubung) Bumi", "The thick layer of hot rock between the crust and the core.", "Lapisan tebal batuan panas di antara kerak dan inti Bumi."],
  ["plate-tectonics", "tectonic plate", "lempeng tektonik", "A large slab of the Earth's lithosphere that moves slowly.", "Bongkahan besar litosfer Bumi yang bergerak perlahan."],
  ["plate-tectonics", "subduction", "subduksi (penunjaman)", "One plate sinking beneath another at a convergent boundary.", "Menunjamnya satu lempeng ke bawah lempeng lain di batas konvergen."],
  ["rocks", "igneous rock", "batuan beku", "Rock formed when magma or lava cools and solidifies.", "Batuan yang terbentuk ketika magma atau lava mendingin dan membeku."],
  ["rocks", "sedimentary rock", "batuan sedimen", "Rock formed from layers of sediment pressed together.", "Batuan yang terbentuk dari lapisan endapan yang termampatkan."],
  ["rocks", "metamorphic rock", "batuan metamorf (malihan)", "Rock changed by heat and pressure.", "Batuan yang berubah karena panas dan tekanan."],
  ["volcanism", "magma", "magma", "Molten rock beneath the Earth's surface.", "Batuan cair pijar di bawah permukaan Bumi."],
  ["volcanism", "pyroclastic flow", "awan panas (aliran piroklastik)", "A fast, very hot flow of gas and volcanic debris down a volcano.", "Aliran gas dan material vulkanik yang sangat panas dan cepat menuruni lereng gunung api."],
  ["earthquakes", "epicentre", "episentrum", "The point on the surface directly above where an earthquake starts.", "Titik di permukaan tepat di atas tempat gempa bermula."],
  ["earthquakes", "magnitude", "magnitudo", "A measure of the energy released by an earthquake.", "Ukuran energi yang dilepaskan oleh gempa bumi."],
  ["earthquakes", "tsunami", "tsunami", "A series of large sea waves caused by a sudden movement of the sea floor.", "Rangkaian gelombang laut besar akibat gerakan tiba-tiba dasar laut."],
  ["weathering", "weathering", "pelapukan", "The breaking down of rocks in place by weather, water, chemicals or living things.", "Penghancuran batuan di tempatnya oleh cuaca, air, zat kimia, atau makhluk hidup."],
  ["weathering", "erosion", "erosi", "The removal and transport of soil and rock by water, wind or ice.", "Pengikisan dan pengangkutan tanah dan batuan oleh air, angin, atau es."],
  ["landforms", "delta", "delta", "A landform built of sediment where a river enters the sea or a lake.", "Bentang alam dari endapan di tempat sungai bermuara ke laut atau danau."],
  ["soils", "soil horizon", "horizon tanah", "A layer of soil that differs from the layers above and below.", "Lapisan tanah yang berbeda dari lapisan di atas dan di bawahnya."],
  ["atmosphere-layers", "troposphere", "troposfer", "The lowest layer of the atmosphere, where weather happens.", "Lapisan atmosfer terbawah, tempat terjadinya cuaca."],
  ["atmosphere-layers", "ozone layer", "lapisan ozon", "The layer in the stratosphere that absorbs most harmful ultraviolet light.", "Lapisan di stratosfer yang menyerap sebagian besar sinar ultraviolet berbahaya."],
  ["weather-elements", "weather", "cuaca", "The state of the atmosphere at a place over a short time.", "Keadaan atmosfer di suatu tempat dalam waktu singkat."],
  ["weather-elements", "humidity", "kelembapan udara", "The amount of water vapour in the air.", "Banyaknya uap air di udara."],
  ["winds", "air pressure", "tekanan udara", "The force of the weight of the air above a surface.", "Gaya dari berat udara di atas suatu permukaan."],
  ["winds", "monsoon", "angin muson", "A seasonal wind that reverses direction between summer and winter.", "Angin musiman yang berganti arah antara musim panas dan musim dingin."],
  ["precipitation", "orographic rain", "hujan orografis", "Rain formed when moist air is forced up a mountain and cools.", "Hujan yang terjadi ketika udara lembap dipaksa naik ke gunung lalu mendingin."],
  ["climate-types", "climate", "iklim", "The average weather of a region over a long period, usually 30 years.", "Rata-rata cuaca suatu wilayah dalam jangka panjang, biasanya 30 tahun."],
  ["climate-change", "global warming", "pemanasan global", "The rise in the average temperature of the Earth's surface.", "Kenaikan suhu rata-rata permukaan Bumi."],
  ["climate-change", "greenhouse gas", "gas rumah kaca", "A gas such as CO₂ or methane that traps heat in the atmosphere.", "Gas seperti CO₂ atau metana yang memerangkap panas di atmosfer."],
  ["water-cycle", "water cycle", "siklus air (hidrologi)", "The continuous movement of water between the sea, air and land.", "Perputaran air yang terus-menerus antara laut, udara, dan daratan."],
  ["water-cycle", "evaporation", "penguapan (evaporasi)", "The change of liquid water into water vapour.", "Perubahan air cair menjadi uap air."],
  ["rivers", "drainage basin", "daerah aliran sungai (DAS)", "The area of land drained by a river and its tributaries.", "Wilayah daratan yang airnya dialirkan oleh sungai beserta anak-anak sungainya."],
  ["groundwater", "aquifer", "akuifer", "A layer of rock or sediment that stores and transmits groundwater.", "Lapisan batuan atau endapan yang menyimpan dan mengalirkan air tanah."],
  ["groundwater", "water table", "muka air tanah", "The upper surface of the saturated zone underground.", "Permukaan atas zona jenuh air di bawah tanah."],
  ["oceans", "continental shelf", "landas kontinen", "The shallow sea floor at the edge of a continent.", "Dasar laut dangkal di tepi benua."],
  ["tides-coasts", "tide", "pasang surut", "The regular rise and fall of sea level caused by the Moon and Sun.", "Naik turunnya permukaan laut secara teratur akibat Bulan dan Matahari."],
  ["tides-coasts", "abrasion", "abrasi", "Erosion of the coast by waves.", "Pengikisan pantai oleh gelombang laut."],
  ["biogeography", "biodiversity", "keanekaragaman hayati", "The variety of living things in an area.", "Keragaman makhluk hidup di suatu wilayah."],
  ["biogeography", "endemic species", "spesies endemik", "A species found naturally in only one region.", "Spesies yang secara alami hanya ditemukan di satu wilayah."],
  ["biomes", "biome", "bioma", "A large community of plants and animals shaped by climate, such as a tropical rainforest.", "Komunitas besar tumbuhan dan hewan yang dibentuk oleh iklim, misalnya hutan hujan tropis."],
  ["conservation", "conservation", "konservasi", "The protection and careful use of nature and resources.", "Perlindungan dan pemanfaatan alam serta sumber daya secara bijak."],
  ["population-growth", "birth rate", "angka kelahiran", "The number of births per 1,000 people per year.", "Banyaknya kelahiran per 1.000 penduduk per tahun."],
  ["population-growth", "death rate", "angka kematian", "The number of deaths per 1,000 people per year.", "Banyaknya kematian per 1.000 penduduk per tahun."],
  ["population-growth", "population density", "kepadatan penduduk", "The number of people per square kilometre.", "Banyaknya penduduk per kilometer persegi."],
  ["population-structure", "population pyramid", "piramida penduduk", "A graph showing a population by age group and sex.", "Grafik yang menggambarkan penduduk menurut kelompok umur dan jenis kelamin."],
  ["population-structure", "dependency ratio", "rasio ketergantungan", "The number of dependants (young and old) per 100 people of working age.", "Banyaknya penduduk usia tidak produktif per 100 penduduk usia produktif."],
  ["migration", "urbanisation", "urbanisasi", "The growth in the share of people living in towns and cities.", "Bertambahnya proporsi penduduk yang tinggal di kota."],
  ["migration", "migration", "migrasi", "The movement of people from one place to live in another.", "Perpindahan penduduk dari satu tempat untuk menetap di tempat lain."],
  ["demographic-transition", "demographic transition", "transisi demografi", "The change from high to low birth and death rates as a country develops.", "Perubahan dari angka kelahiran dan kematian tinggi menjadi rendah seiring berkembangnya negara."],
  ["human-development", "Human Development Index (HDI)", "Indeks Pembangunan Manusia (IPM)", "A measure combining life expectancy, education and income.", "Ukuran gabungan dari harapan hidup, pendidikan, dan pendapatan."],
  ["resources", "renewable resource", "sumber daya terbarukan", "A resource that is naturally replaced, such as forests or sunlight.", "Sumber daya yang dapat pulih secara alami, misalnya hutan atau sinar matahari."],
  ["agriculture", "intensification", "intensifikasi", "Raising farm output from the same land with better methods and inputs.", "Meningkatkan hasil pertanian dari lahan yang sama dengan cara dan sarana yang lebih baik."],
  ["industry-location", "agglomeration", "aglomerasi", "The clustering of industries in one area to share services and markets.", "Pengelompokan industri di satu wilayah untuk berbagi layanan dan pasar."],
  ["central-places", "central place", "tempat sentral", "A settlement that provides goods and services to the surrounding area.", "Permukiman yang menyediakan barang dan jasa bagi wilayah sekitarnya."],
  ["spatial-interaction", "spatial interaction", "interaksi keruangan", "The flow of people, goods and information between places.", "Arus penduduk, barang, dan informasi antarwilayah."],
  ["rural-urban", "suburbanisation", "suburbanisasi", "The movement of people from city centres to the outskirts.", "Perpindahan penduduk dari pusat kota ke daerah pinggiran."],
  ["regional-development", "growth centre", "pusat pertumbuhan", "A place chosen for investment to spread development to its region.", "Tempat yang dipilih untuk investasi agar pembangunan menyebar ke wilayah sekitarnya."],
  ["disasters", "disaster mitigation", "mitigasi bencana", "Actions taken to reduce the risk and impact of disasters.", "Upaya untuk mengurangi risiko dan dampak bencana."],
  ["sustainability", "sustainable development", "pembangunan berkelanjutan", "Development that meets present needs without harming the needs of future generations.", "Pembangunan yang memenuhi kebutuhan sekarang tanpa merugikan kebutuhan generasi mendatang."],
  ["indonesia-position", "archipelagic state", "negara kepulauan", "A state made up of groups of islands with the waters between them.", "Negara yang terdiri atas gugusan pulau beserta perairan di antaranya."],
  ["indonesia-position", "Exclusive Economic Zone (EEZ)", "Zona Ekonomi Eksklusif (ZEE)", "The sea zone up to 200 nautical miles from the baseline where a country controls resources.", "Zona laut hingga 200 mil laut dari garis pangkal tempat suatu negara berhak atas sumber dayanya."],
  ["geopolitics", "geopolitics", "geopolitik", "How geography shapes a country's politics and relations with others.", "Pengaruh keadaan geografis terhadap politik suatu negara dan hubungannya dengan negara lain."],
  ["development-levels", "developed country", "negara maju", "A country with high income, industry and quality of life.", "Negara dengan pendapatan, industri, dan kualitas hidup yang tinggi."],
  ["cooperation", "ASEAN", "ASEAN", "The Association of Southeast Asian Nations, founded in 1967.", "Perhimpunan Bangsa-Bangsa Asia Tenggara, didirikan pada 1967."],
  ["spatial-analysis", "spatial analysis", "analisis spasial", "Methods for finding patterns and relationships in geographic data.", "Metode untuk menemukan pola dan hubungan dalam data geografis."],
  ["hydrology", "discharge", "debit", "The volume of water flowing past a point in a river per second.", "Volume air yang melewati suatu titik di sungai per detik."],
  ["cartography", "cartography", "kartografi", "The science and art of making maps.", "Ilmu dan seni membuat peta."],
  ["research-methods", "sampling", "pengambilan sampel", "Choosing a representative part of a population or area to study.", "Memilih sebagian populasi atau wilayah yang mewakili untuk diteliti."]
];
